language: go

go:
  - 1.14

jobs:
  include:
    - stage: "Lint"
      script:
        - go mod tidy && ( [ -z "$(git status -s)" ] || (echo "$(git diff)" && false) )
        - make lint
        
    - stage: "Test"
      name: "Tests"
      before_install:
        - go get github.com/mattn/goveralls
        - go mod download

      script:
        - cd catalogc && go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out && cd ../
        - cd domanager/app && go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out && cd ../../
        - cd dsmanager/app && go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out && cd ../../
        - cd enclavem/app && go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out && cd ../../
        - cd projectc && go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out && cd ../
        - cd cryptutil && ./test.sh

notifications:
  email: false
