language: go

go:
  - 1.14

jobs:
  include:
    - stage: "Lint"
      script:
        - go mod tidy && echo "$(git diff)" && [ -z "$(git status -s)" ]
        - make lint
        
    - stage: "Test"
      name: "Tests"
      before_install:
        - go get github.com/mattn/goveralls
        - go mod download

      script:
        - go test -covermode=count -coverprofile=coverage.out ./...
        - $GOPATH/bin/goveralls -service=travis-cli -coverprofile=coverage.out

notifications:
  email: false
