@startuml

interface "HTTP" as http1
interface "HTTP" as http2

component [cothority]

node "Datas scientist manager" {
    http1 - [ds app]

    interface "Go exec" as goexec1
    component [bcadmin] as bcadmin1
    goexec1 -down- [bcadmin1]
    [ds app] --> goexec1
    
    interface "Go exec" as goexec2
    component [csadmin] as csadmin1
    goexec2 -down- [csadmin1]
    [ds app] --> goexec2
    
    interface "Go exec" as goexec3
    component [pcadmin] as pcadmin1
    goexec3 -down- [pcadmin1]
    [ds app] --> goexec3

    [ds app] --> http2

    [bcadmin1] -> [cothority]
    [pcadmin1] -> [cothority]
    [csadmin1] -> [cothority]
}

[Browser] --> http1

interface "HTTP" as http_vcloud
interface "HTTP" as http_cloud

http_vcloud - [VMware vCloud] 

node "Enclave manager" {
    interface "Go exec" as goexec4
    component [bcadmin] as bcadmin2
    goexec4 -down- [bcadmin2]
    [em app] --> goexec4
    
    interface "Go exec" as goexec5
    component [csadmin] as csadmin2
    goexec5 -down- [csadmin2]
    [em app] --> goexec5
    
    interface "Go exec" as goexec6
    component [pcadmin] as pcadmin2
    goexec6 -down- [pcadmin2]
    [em app] --> goexec6

    http2 - [em app]
    
    
    [em app] --> http_vcloud
    [em app] --> http_cloud
    
    [bcadmin2] -> [cothority]
    [pcadmin2] -> [cothority]
    [csadmin2] -> [cothority]
}

node "vApp (enclave instance)" {
    interface "Go exec" as goexec7
    component [bcadmin] as bcadmin3
    goexec7 -down- [bcadmin3]
    
    [Ubuntu] --> goexec7
    [Ubuntu] --> http_cloud
    
    [bcadmin3] -> [cothority]
}

[VMware vCloud] --> [Ubuntu]

http_cloud - [Cloud provider]

@enduml